/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gdep;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
    @Test
    public void test() {}
}
